platform :ios, '13.0'
use_frameworks!

target 'AppStoreExample' do
    pod "MagicalRecord"
    pod 'Alamofire', '~> 5.1'
    pod 'AlamofireImage', '~> 4.1'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
    
  target 'AppStoreExampleTests' do
    inherit! :search_paths
  end
end
