source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'AppStoreExample' do
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
    
  target 'AppStoreExampleTests' do
    inherit! :search_paths
  end
end
